apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: surfersweb
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: surferslookout
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/language: python
    apps.tanzu.vmware.com/workload-type: web
    component: frontend
    app.kubernetes.io/component: run
    carto.run/workload-name: surfersweb
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: https://github.com/davlloyd/surfers-web?sub_path=/
        autoscaling.knative.dev/initial-scale: "1"
        autoscaling.knative.dev/max-scale: "50"
        autoscaling.knative.dev/metric: rps
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/scale-down-delay: 2s
        autoscaling.knative.dev/target: "60"
        autoscaling.knative.dev/window: 10s
        conventions.carto.run/applied-conventions: |-
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/is-native-app-check
          spring-boot-convention/is-prometheus-enabled-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"surferslookout","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/language":"python","apps.tanzu.vmware.com/workload-type":"web","component":"frontend"},"name":"surfersweb","namespace":"alpha"},"spec":{"env":[{"name":"GOOGLE_API_KEY","value":"AIzaSyClGDVij1cDFxSg9T034eayd8cZgnljRYA"}],"params":[{"name":"clusterBuilder","value":"default"},{"name":"testing_pipeline_matching_labels","value":{"apps.tanzu.vmware.com/language":"python"}},{"name":"annotations","value":{"autoscaling.knative.dev/initial-scale":"1","autoscaling.knative.dev/max-scale":"50","autoscaling.knative.dev/metric":"rps","autoscaling.knative.dev/min-scale":"1","autoscaling.knative.dev/scale-down-delay":"2s","autoscaling.knative.dev/target":"60","autoscaling.knative.dev/window":"10s"}},{"name":"git_user_email","value":"davidlloyd0@gmail.com"},{"name":"git_user_name","value":"davlloyd"}],"serviceClaims":[{"name":"db","ref":{"apiVersion":"v1","kind":"Secret","name":"surferslookout-db"}},{"name":"api","ref":{"apiVersion":"v1","kind":"Secret","name":"surfersweb-api"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/davlloyd/surfers-web"}}}}
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: surferslookout
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/language: python
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: surfersweb
        component: frontend
    spec:
      containers:
      - env:
        - name: GOOGLE_API_KEY
          value: AIzaSyClGDVij1cDFxSg9T034eayd8cZgnljRYA
        image: harbor.home.tanzu.rocks/tap/supply-chain/surfersweb-alpha@sha256:2b871647383a5d8eafd17eec6d89adfdf0e76e78df10b2d9cd5812786467ee3b
        name: workload
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: default

